# Generated by Django 3.0.4 on 2020-05-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctitle', models.TextField(max_length=50)),
                ('cdescription', models.TextField(max_length=200)),
                ('cpassword', models.TextField(null=True)),
                ('cbeginingdate', models.CharField(default='05/06/2020', max_length=20)),
                ('cbeginingtime', models.CharField(default='07:00 PM', max_length=20)),
                ('clength', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ranklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(max_length=50)),
                ('contestid', models.IntegerField(default=0)),
                ('spb1', models.BooleanField(default=False, null=True)),
                ('spb2', models.BooleanField(default=False, null=True)),
                ('spb3', models.BooleanField(default=False, null=True)),
                ('spb4', models.BooleanField(default=False, null=True)),
                ('spb5', models.BooleanField(default=False, null=True)),
                ('spb6', models.BooleanField(default=False, null=True)),
                ('spb7', models.BooleanField(default=False, null=True)),
                ('spb8', models.BooleanField(default=False, null=True)),
                ('spb9', models.BooleanField(default=False, null=True)),
                ('spb10', models.BooleanField(default=False, null=True)),
                ('tpb1', models.DecimalField(decimal_places=4, default=0.0, max_digits=19)),
                ('tpb2', models.DecimalField(decimal_places=4, default=0.0, max_digits=19)),
                ('tpb3', models.DecimalField(decimal_places=4, default=0.0, max_digits=19)),
                ('tpb4', models.DecimalField(decimal_places=4, default=0.0, max_digits=19)),
                ('tpb5', models.DecimalField(decimal_places=4, default=0.0, max_digits=19)),
                ('tpb6', models.DecimalField(decimal_places=4, default=0.0, max_digits=19)),
                ('tpb7', models.DecimalField(decimal_places=4, default=0.0, max_digits=19)),
                ('tpb8', models.DecimalField(decimal_places=4, default=0.0, max_digits=19)),
                ('tpb9', models.DecimalField(decimal_places=4, default=0.0, max_digits=19)),
                ('tpb10', models.DecimalField(decimal_places=4, default=0.0, max_digits=19)),
            ],
        ),
    ]
