# Generated by Django 3.0.4 on 2020-05-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='contestants',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='problems',
            field=models.TextField(default='', null=True),
        ),
    ]
