# Generated by Django 3.0.4 on 2020-03-16 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=2000)),
                ('input', models.CharField(max_length=500)),
                ('output', models.CharField(max_length=500)),
                ('note', models.CharField(max_length=500, null=True)),
                ('Contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.Contest')),
            ],
        ),
    ]
