# Generated by Django 3.0.4 on 2020-05-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_auto_20200513_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranklist',
            name='totalac',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ranklist',
            name='totalpoint',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ranklist',
            name='tpb1',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ranklist',
            name='tpb10',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ranklist',
            name='tpb2',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ranklist',
            name='tpb3',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ranklist',
            name='tpb4',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ranklist',
            name='tpb5',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ranklist',
            name='tpb6',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ranklist',
            name='tpb7',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ranklist',
            name='tpb8',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ranklist',
            name='tpb9',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=19),
        ),
    ]
