# Generated by Django 3.0.4 on 2020-05-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_problem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='end_time',
            new_name='cbeginingtime',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='description',
            new_name='cdescription',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='start_time',
            new_name='clength',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='password',
            new_name='cpassword',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='title',
            new_name='ctitle',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='last_update_time',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='rule_type',
        ),
        migrations.AlterField(
            model_name='contest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
    ]
