# Generated by Django 3.0.4 on 2020-05-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_auto_20200514_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranklist',
            name='totalac',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ranklist',
            name='totalpoint',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=19),
        ),
    ]
