# Generated by Django 3.0.4 on 2020-05-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_auto_20200506_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='cbeginingtime',
            field=models.TextField(),
        ),
    ]
