# Generated by Django 3.0.4 on 2020-05-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_auto_20200506_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='cbeginingdate',
            field=models.CharField(default='05/06/2020', max_length=20),
        ),
        migrations.AlterField(
            model_name='contest',
            name='cbeginingtime',
            field=models.CharField(default='07:00 PM', max_length=20),
        ),
        migrations.AlterField(
            model_name='contest',
            name='clength',
            field=models.CharField(max_length=20),
        ),
    ]
