# Generated by Django 3.0.4 on 2020-05-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_auto_20200514_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranklist',
            name='totalpoint',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=19),
        ),
    ]
