# Generated by Django 3.0.4 on 2020-05-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_auto_20200514_0505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submissionid', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(default='', max_length=50, null=True)),
                ('contestid', models.IntegerField(null=True)),
                ('code', models.TextField(default='', null=True)),
                ('language', models.CharField(default='', max_length=50, null=True)),
                ('status', models.CharField(default='', max_length=50, null=True)),
            ],
        ),
    ]
