# Generated by Django 3.0.4 on 2020-05-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptitle', models.CharField(max_length=100)),
                ('ptimelim', models.IntegerField()),
                ('pmemorylim', models.IntegerField()),
                ('pdescription', models.TextField()),
                ('pinput', models.TextField()),
                ('poutput', models.TextField()),
                ('pexinput', models.TextField()),
                ('pexoutput', models.TextField()),
                ('ptags', models.TextField()),
                ('ptype', models.CharField(max_length=100)),
                ('pnote', models.TextField()),
            ],
        ),
    ]
