# Generated by Django 3.0.4 on 2020-05-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(default='1', max_length=10)),
                ('ptitle', models.CharField(max_length=100)),
                ('ptimelimit', models.IntegerField(blank=True, null=True)),
                ('pmemorylimit', models.IntegerField(blank=True, null=True)),
                ('pdescription', models.TextField(blank=True, null=True)),
                ('pinput', models.TextField(blank=True, null=True)),
                ('poutput', models.TextField(blank=True, null=True)),
                ('pexinput', models.TextField(blank=True, null=True)),
                ('pexoutput', models.TextField(blank=True, null=True)),
                ('ptags', models.TextField(blank=True, null=True)),
                ('ptype', models.CharField(max_length=100)),
                ('pnote', models.TextField(null=True)),
                ('pshow', models.CharField(default='No', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Submitted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(default='', max_length=10)),
                ('psubmit', models.IntegerField(default=0)),
                ('pac', models.IntegerField(default=0)),
                ('pwa', models.IntegerField(default=0)),
            ],
        ),
    ]
