# Generated by Django 3.0.4 on 2020-05-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_auto_20200508_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='ptags',
            field=models.TextField(null=True),
        ),
    ]
