# Generated by Django 3.0.4 on 2020-05-08 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_problem_pid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='pmemorylim',
            new_name='pmemorylimit',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='ptimelim',
            new_name='ptimelimit',
        ),
    ]
