# Generated by Django 3.0.4 on 2020-05-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_auto_20200509_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='pshow',
            field=models.CharField(default='No', max_length=10),
        ),
    ]
