# Generated by Django 3.0.4 on 2021-07-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='picname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='picurl',
        ),
        migrations.AddField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic'),
        ),
    ]
